ARG CERVER_VERSION=2.0b-45

ARG BUILD_DEPS='ca-certificates libssl-dev gdb'

FROM ermiry/mongoc:builder

ARG BUILD_DEPS
RUN apt-get update && apt-get install -y ${BUILD_DEPS}

# cerver
ARG CERVER_VERSION
RUN mkdir /opt/cerver && cd /opt/cerver \
    && wget -q https://github.com/ermiry/cerver/archive/${CERVER_VERSION}.zip \
    && unzip ${CERVER_VERSION}.zip \
    && cd cerver-${CERVER_VERSION} \
    && make -j4 && make install

RUN ldconfig

# videos
WORKDIR /home/videos

CMD ["/bin/bash"]
